sonobuoy-config:
  driver: Job
  plugin-name: depthcharge
  result-format: raw
spec:
  command:
  - ./run.sh
  image: negz/depthcharge:v0.1
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/results
    name: results

